### ISSUE TITLE
Create a Class Object that contains

### ISSUE THREAD

**Issue by NataliaLopez17** [uprm-inso-4101-2020-2021-S1/semester-project-almond-software-llc#4]
- Section Object(s)
- Name
- Description
- Department (Perhaps as a parent object)
- Pre-requesites

**Comment by igtampe** [comment]
To avoid having a class named ```class``` I suggest we name it ```course``` instead.

Also, over on the ```department``` class, in order to store the courses for easy lookup, we're using a hashtable to hold them. Please have the course number (IE 3101 from ICOM3101) as a *separate* variable (IE Course.Number)
